server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:h2:mem:testdb 
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
        
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console  

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.catalogservice: DEBUG

catalog:
  topic:
    name: example-order-topic